# -*- coding: utf-8 -*-
{
    'name': "Zatca E-invoice",
    'summary': """This Module is used for connecting zatca portal and xml creation""",
    'description': """This Module is used for connecting zatca portal and xml creation""",
    # 'live_test_url': 'https://youtu.be/Fy93tJCzV2k',
    "author": "Enzapps",
    "website": "www.enzapps.com",
    'license': 'AGPL-3',
    'images': ['static/description/cover.png', 'static/description/icon.png'],
    'category': 'Invoicing',
    'version': '14.0',
    'price': 399, 'currency': 'USD',
    'depends': ['account', 'sale', 'l10n_sa_invoice', 'purchase', 'account_debit_note'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/res_config_settings.xml',
        'views/res_partner.xml',
        'views/res_company.xml',
        'views/account_move.xml',
        'views/account_tax.xml',
        'views/product_product.xml',
        'views/eway_config.xml',
    ],
}
